=== AnLau25/COMP466/TMA1/part1/resume.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           targetNamespace="http://part1.com/resume" 
           xmlns="http://part1.com/resume"
           elementFormDefault="qualified">
    <xs:element name="resume">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="geninfo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="age" type="xs:integer" />
                            <xs:element name="hobbies" type="xs:string" />
                            <xs:element name="edubg">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="uni" type="xs:string" />
                                        <xs:element name="major" type="xs:string" />
                                        <xs:element name="prev" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="workinfo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="position" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="description" type="xs:string" />
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AnLau25/COMP466/TMA1/part1/resume.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="resume.xsl"?>
<resume xmlns="http://part1.com/resume"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://part1.com/resume resume.xsd">
    <geninfo>
        <name>Ana Laura Valdés</name>
        <age>21</age>
        <hobbies>Fútbol, F1</hobbies>
        <edubg>
            <uni>University of Ottawa</uni>
            <major>Software Engineering</major>
            <prev>Collège catholique Samuel-Genest</prev>
        </edubg>
    </geninfo>
    <workinfo>
        <position id="CISSSO">
            <description>Intern in Operational Security</description>
        </position>
        <position id="Shoppers">
            <description>Pharmacy Assistant</description>
        </position>
    </workinfo>
</resume>
